// Generated by Grafana k6 Studio (1.9.0) on 2025-11-26T07:59:32.111Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/`;
    resp = http.request("GET", url, null, params1);
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":4,"feature":1,"property":"error","value":false},{"type":"mSync","node":4,"feature":1,"property":"action","value":null},{"type":"mSync","node":4,"feature":1,"property":"disabled","value":false}],"syncId":0,"clientId":0}`,
      params2,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/offline.html`;
    resp = http.request("GET", url, null, params3);
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"event","node":4,"event":"login","data":{"event.detail.username":"admin","event.detail.password":"admin"}},{"type":"mSync","node":4,"feature":1,"property":"disabled","value":true}],"syncId":1,"clientId":1}`,
      params2,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":81,"feature":1,"property":"drawerOpened","value":true},{"type":"mSync","node":81,"feature":1,"property":"primarySection","value":"navbar"},{"type":"mSync","node":81,"feature":1,"property":"overlay","value":false},{"type":"publishedEventHandler","node":60,"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[0],"promise":0}],"syncId":2,"clientId":2}`,
      params2,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"channel","node":1,"channel":0,"args":[{"v-sh":"1440","v-sw":"2560","v-wh":"1232","v-ww":"1200","v-bh":"1232","v-bw":"1200","v-curdate":"1764142198040","v-tzo":"-120","v-dstd":"60","v-rtzo":"-120","v-dston":"false","v-tzid":"Europe/Helsinki","v-wn":"ROOT-2521314-0.36852521681833117","v-td":"false","v-pr":"2","v-np":"MacIntel"}]},{"type":"channel","node":64,"channel":0,"args":[null]},{"type":"channel","node":64,"channel":2,"args":[null]},{"type":"publishedEventHandler","node":60,"templateEventMethodName":"setRequestedRange","templateEventMethodArgs":[0,150],"promise":1}],"syncId":3,"clientId":3}`,
      params2,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"publishedEventHandler","node":60,"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[1],"promise":2}],"syncId":4,"clientId":4}`,
      params2,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"event","node":63,"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":1,"event.ctrlKey":false,"event.clientX":1082,"event.clientY":89,"event.altKey":false,"event.button":0,"event.screenY":223,"event.screenX":2904}}],"syncId":5,"clientId":5}`,
      params2,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"event","node":51,"event":"value-changed","data":{}},{"type":"event","node":49,"event":"value-changed","data":{}},{"type":"event","node":46,"event":"value-changed","data":{}},{"type":"event","node":45,"event":"value-changed","data":{}},{"type":"event","node":37,"event":"value-changed","data":{}},{"type":"event","node":36,"event":"checked-changed","data":{}},{"type":"event","node":34,"event":"checked-changed","data":{}},{"type":"event","node":32,"event":"checked-changed","data":{}},{"type":"event","node":30,"event":"checked-changed","data":{}},{"type":"event","node":28,"event":"checked-changed","data":{}},{"type":"event","node":26,"event":"checked-changed","data":{}},{"type":"event","node":24,"event":"checked-changed","data":{}},{"type":"event","node":22,"event":"checked-changed","data":{}}],"syncId":6,"clientId":6}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"channel","node":51,"channel":0,"args":[null]},{"type":"channel","node":51,"channel":2,"args":[null]},{"type":"channel","node":49,"channel":0,"args":[null]},{"type":"channel","node":49,"channel":2,"args":[null]},{"type":"channel","node":46,"channel":0,"args":[null]},{"type":"channel","node":46,"channel":2,"args":[null]}],"syncId":7,"clientId":7}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"B"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":8,"clientId":8}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Bo"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":9,"clientId":9}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Boo"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":10,"clientId":10}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":11,"clientId":11}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book "},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":12,"clientId":12}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book o"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":13,"clientId":13}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":14,"clientId":14}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of "},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":15,"clientId":15}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of V"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":16,"clientId":16}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of Va"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":17,"clientId":17}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of Vaa"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":18,"clientId":18}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of Vaad"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":19,"clientId":19}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of Vaadi"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":20,"clientId":20}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":51,"feature":1,"property":"value","value":"Book of Vaadin"},{"type":"event","node":51,"event":"value-changed","data":{}}],"syncId":21,"clientId":21}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":49,"feature":1,"property":"value","value":"1.00"},{"type":"event","node":49,"event":"value-changed","data":{}}],"syncId":22,"clientId":22}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":46,"feature":1,"property":"value","value":"1"},{"type":"event","node":46,"event":"value-changed","data":{}}],"syncId":23,"clientId":23}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":46,"feature":1,"property":"value","value":"10"},{"type":"event","node":46,"event":"value-changed","data":{}}],"syncId":24,"clientId":24}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":46,"feature":1,"property":"value","value":"100"},{"type":"event","node":46,"event":"value-changed","data":{}}],"syncId":25,"clientId":25}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":24,"feature":1,"property":"checked","value":true},{"type":"event","node":24,"event":"checked-changed","data":{}},{"type":"mSync","node":37,"feature":1,"property":"invalid","value":null},{"type":"mSync","node":37,"feature":1,"property":"value","value":["7"]},{"type":"event","node":37,"event":"value-changed","data":{}}],"syncId":26,"clientId":26}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":37,"feature":1,"property":"invalid","value":null}],"syncId":27,"clientId":27}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"event","node":20,"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":1,"event.ctrlKey":false,"event.clientX":1037,"event.clientY":683,"event.altKey":false,"event.button":0,"event.screenY":817,"event.screenX":2859}}],"syncId":28,"clientId":28}`,
      params4,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"event","node":96,"event":"opened-changed"},{"type":"publishedEventHandler","node":60,"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[2],"promise":3}],"syncId":29,"clientId":29}`,
      params5,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"event","node":96,"event":"opened-changed"},{"type":"mSync","node":96,"feature":1,"property":"opened","value":false}],"syncId":30,"clientId":30}`,
      params5,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"mSync","node":64,"feature":1,"property":"value","value":"vaadin"},{"type":"event","node":64,"event":"change","data":{}}],"syncId":31,"clientId":31}`,
      params5,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"publishedEventHandler","node":60,"templateEventMethodName":"setRequestedRange","templateEventMethodArgs":[0,50],"promise":4},{"type":"publishedEventHandler","node":60,"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[3],"promise":5}],"syncId":32,"clientId":32}`,
      params5,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=uidl&v-uiId=0`;
    resp = http.request(
      "POST",
      url,
      `{"csrfToken":"3accb0b8-d128-45fb-97eb-703315fd0666","rpc":[{"type":"publishedEventHandler","node":60,"templateEventMethodName":"select","templateEventMethodArgs":["101"],"promise":6},{"type":"publishedEventHandler","node":60,"templateEventMethodName":"setDetailsVisible","templateEventMethodArgs":["101"],"promise":7}],"syncId":33,"clientId":33}`,
      params5,
    );
    check(resp, { "status equals 200": (r) => r.status === 200 });

    url = http.url`https://vaadin-bookstore-example.demo.vaadin.com/?v-r=heartbeat&v-uiId=0`;
    resp = http.request("POST", url, null, params6);
    check(resp, { "status equals 200": (r) => r.status === 200 });

  });
  sleep(1);
}

let params1 = {
  headers: {
    "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
    "sec-ch-ua-mobile": `?0`,
    "sec-ch-ua-platform": `"macOS"`,
    "upgrade-insecure-requests": `1`,
    accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
    "sec-fetch-site": `none`,
    "sec-fetch-mode": `navigate`,
    "sec-fetch-user": `?1`,
    "sec-fetch-dest": `document`,
    "accept-encoding": `gzip, deflate, br, zstd`,
    "accept-language": `en-US,en;q=0.9`,
    priority: `u=0, i`,
  },
  cookies: {},
};

let params2 = {
  headers: {
    "sec-ch-ua-platform": `"macOS"`,
    "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
    "content-type": `application/json; charset=UTF-8`,
    "sec-ch-ua-mobile": `?0`,
    accept: `*/*`,
    origin: `https://vaadin-bookstore-example.demo.vaadin.com`,
    "sec-fetch-site": `same-origin`,
    "sec-fetch-mode": `cors`,
    "sec-fetch-dest": `empty`,
    referer: `https://vaadin-bookstore-example.demo.vaadin.com/`,
    "accept-encoding": `gzip, deflate, br, zstd`,
    "accept-language": `en-US,en;q=0.9`,
    priority: `u=1, i`,
  },
  cookies: {},
};

let params3 = {
  headers: {
    pragma: `no-cache`,
    "cache-control": `no-cache`,
    accept: `*/*`,
    "sec-fetch-site": `same-origin`,
    "sec-fetch-mode": `cors`,
    "sec-fetch-dest": `empty`,
    referer: `https://vaadin-bookstore-example.demo.vaadin.com/sw.js`,
    "accept-encoding": `gzip, deflate, br, zstd`,
    "accept-language": `en-US,en;q=0.9`,
    priority: `u=1, i`,
  },
  cookies: {},
};

let params4 = {
  headers: {
    "sec-ch-ua-platform": `"macOS"`,
    "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
    "content-type": `application/json; charset=UTF-8`,
    "sec-ch-ua-mobile": `?0`,
    accept: `*/*`,
    origin: `https://vaadin-bookstore-example.demo.vaadin.com`,
    "sec-fetch-site": `same-origin`,
    "sec-fetch-mode": `cors`,
    "sec-fetch-dest": `empty`,
    referer: `https://vaadin-bookstore-example.demo.vaadin.com/Inventory/new`,
    "accept-encoding": `gzip, deflate, br, zstd`,
    "accept-language": `en-US,en;q=0.9`,
    priority: `u=1, i`,
  },
  cookies: {},
};

let params5 = {
  headers: {
    "sec-ch-ua-platform": `"macOS"`,
    "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
    "content-type": `application/json; charset=UTF-8`,
    "sec-ch-ua-mobile": `?0`,
    accept: `*/*`,
    origin: `https://vaadin-bookstore-example.demo.vaadin.com`,
    "sec-fetch-site": `same-origin`,
    "sec-fetch-mode": `cors`,
    "sec-fetch-dest": `empty`,
    referer: `https://vaadin-bookstore-example.demo.vaadin.com/Inventory/`,
    "accept-encoding": `gzip, deflate, br, zstd`,
    "accept-language": `en-US,en;q=0.9`,
    priority: `u=1, i`,
  },
  cookies: {},
};

let params6 = {
  headers: {
    "sec-ch-ua-platform": `"macOS"`,
    "sec-ch-ua": `"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"`,
    "content-type": `text/plain; charset=utf-8`,
    "sec-ch-ua-mobile": `?0`,
    accept: `*/*`,
    origin: `https://vaadin-bookstore-example.demo.vaadin.com`,
    "sec-fetch-site": `same-origin`,
    "sec-fetch-mode": `cors`,
    "sec-fetch-dest": `empty`,
    referer: `https://vaadin-bookstore-example.demo.vaadin.com/Inventory/101`,
    "accept-encoding": `gzip, deflate, br, zstd`,
    "accept-language": `en-US,en;q=0.9`,
    priority: `u=1, i`,
  },
  cookies: {},
};
